[package]
name = "avalon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-sdk = "3.0.1"
clap = "4.4.18"
futures = "0.3.30"
libp2p = "0.53.2"
tokio = "1.35.1"
